import json

# EXACT canonical 20 Indian tourist destinations with full structured metadata
DESTINATIONS_DATA = [
    {
        "id": "delhi",
        "name": "Delhi",
        "state": "Delhi",
        "country": "India",
        "latitude": 28.6139,
        "longitude": 77.2090,
        "hero_image_url": "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1200&q=80",
        "known_for": "History, monuments, food, shopping, nightlife",
        "description": "India's vibrant capital blending ancient Mughal grandeur, colonial boulevards, world-class street food, and bustling shopping bazaars.",
        "rating": 4.8,
        "best_time_to_visit": "October–March",
        "ideal_stay": "2–4 days",
        "budget_per_day": "₹1,500–₹5,000/day",
        "estimated_budget_tier": "₹1,500–₹5,000/day",
        "weather_temperature": "24°C",
        "weather_condition": "Pleasant & Sunny",
        "safety_score": 90,
        "tags": ["Heritage", "Culture", "Food", "Shopping", "Nightlife", "Popular", "Trending"],
        "top_attractions": ["Red Fort", "India Gate", "Qutub Minar", "Humayun's Tomb", "Lotus Temple", "Akshardham", "Jama Masjid", "Chandni Chowk"],
        "activities": ["Heritage walks", "Food tours", "Shopping", "Museums", "Nightlife"],
        "famous_food": ["Chole bhature", "Butter chicken", "Kebabs", "Parathas", "Chaat"],
        "local_transport": ["Metro", "Buses", "Cabs", "Auto"],
        "nearby_places": ["Agra", "Jaipur", "Neemrana", "Mathura"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "mumbai",
        "name": "Mumbai",
        "state": "Maharashtra",
        "country": "India",
        "latitude": 18.9220,
        "longitude": 72.8347,
        "hero_image_url": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Bollywood, beaches, nightlife, business",
        "description": "The City of Dreams with glittering Marine Drive, Victorian architecture, electric nightlife, thriving arts, and irresistible street food.",
        "rating": 4.8,
        "best_time_to_visit": "October–February",
        "ideal_stay": "2–4 days",
        "budget_per_day": "₹2,000–₹6,000/day",
        "estimated_budget_tier": "₹2,000–₹6,000/day",
        "weather_temperature": "28°C",
        "weather_condition": "Coastal Breeze",
        "safety_score": 92,
        "tags": ["Beaches", "Nightlife", "Culture", "Food", "Shopping", "Popular", "Trending"],
        "top_attractions": ["Gateway of India", "Marine Drive", "Elephanta Caves", "Colaba Causeway", "Chhatrapati Shivaji Maharaj Terminus", "Juhu Beach"],
        "activities": ["Bollywood tours", "Sightseeing", "Shopping", "Nightlife", "Street-food tours"],
        "famous_food": ["Vada pav", "Pav bhaji", "Misal pav", "Bombay sandwich"],
        "local_transport": ["Local trains", "Metro", "Buses", "Taxis"],
        "nearby_places": ["Lonavala", "Alibaug", "Pune"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "jaipur",
        "name": "Jaipur",
        "state": "Rajasthan",
        "country": "India",
        "latitude": 26.9124,
        "longitude": 75.7873,
        "hero_image_url": "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Royal heritage, forts, palaces",
        "description": "Rajasthan's enchanting Pink City celebrated for formidable hilltop forts, ornate royal palaces, vibrant gemstones, and regal hospitality.",
        "rating": 4.9,
        "best_time_to_visit": "October–March",
        "ideal_stay": "2–3 days",
        "budget_per_day": "₹1,500–₹5,000/day",
        "estimated_budget_tier": "₹1,500–₹5,000/day",
        "weather_temperature": "25°C",
        "weather_condition": "Clear Sky",
        "safety_score": 94,
        "tags": ["Heritage", "Culture", "Shopping", "Food", "Popular", "Trending"],
        "top_attractions": ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar", "Jal Mahal", "Nahargarh Fort"],
        "activities": ["Fort tours", "Shopping", "Cultural shows", "Photography", "Desert experiences"],
        "famous_food": ["Dal baati churma", "Ghewar", "Pyaaz kachori", "Laal maas"],
        "local_transport": ["Metro", "Auto", "Taxi", "Buses"],
        "nearby_places": ["Ajmer", "Pushkar", "Delhi", "Agra", "Jodhpur", "Udaipur"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "goa",
        "name": "Goa",
        "state": "Goa",
        "country": "India",
        "latitude": 15.2993,
        "longitude": 74.1240,
        "hero_image_url": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Beaches, nightlife, parties, water sports",
        "description": "India's beach capital offering golden shores, Portuguese colonial heritage, exciting watersports, seaside shacks, and sun-soaked nightlife.",
        "rating": 4.9,
        "best_time_to_visit": "November–February",
        "ideal_stay": "3–5 days",
        "budget_per_day": "₹2,000–₹7,000/day",
        "estimated_budget_tier": "₹2,000–₹7,000/day",
        "weather_temperature": "29°C",
        "weather_condition": "Sunny & Breezy",
        "safety_score": 93,
        "tags": ["Beaches", "Nightlife", "Adventure", "Food", "Culture", "Popular", "Trending"],
        "top_attractions": ["Baga Beach", "Calangute", "Anjuna", "Fort Aguada", "Basilica of Bom Jesus", "Panjim"],
        "activities": ["Scuba diving", "Parasailing", "Surfing", "Beach hopping", "Nightlife"],
        "famous_food": ["Goan fish curry", "Pork vindaloo", "Bebinca"],
        "local_transport": ["Scooters", "Taxis", "Buses"],
        "nearby_places": ["Dudhsagar Falls", "Gokarna"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "agra",
        "name": "Agra",
        "state": "Uttar Pradesh",
        "country": "India",
        "latitude": 27.1751,
        "longitude": 78.0421,
        "hero_image_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Taj Mahal and Mughal history",
        "description": "Historic jewel on the Yamuna river, home to the iconic Taj Mahal, majestic Agra Fort, and UNESCO World Heritage Mughal architecture.",
        "rating": 4.9,
        "best_time_to_visit": "October–March",
        "ideal_stay": "1–2 days",
        "budget_per_day": "₹1,200–₹4,000/day",
        "estimated_budget_tier": "₹1,200–₹4,000/day",
        "weather_temperature": "23°C",
        "weather_condition": "Sunny",
        "safety_score": 91,
        "tags": ["Heritage", "Culture", "Food", "Shopping", "Popular", "Trending"],
        "top_attractions": ["Taj Mahal", "Agra Fort", "Mehtab Bagh", "Itmad-ud-Daulah", "Fatehpur Sikri"],
        "activities": ["Heritage tours", "Photography", "Local shopping"],
        "famous_food": ["Petha", "Mughlai cuisine", "Bedai"],
        "local_transport": ["Auto", "Taxi", "E-rickshaw"],
        "nearby_places": ["Delhi", "Jaipur", "Mathura", "Vrindavan"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "varanasi",
        "name": "Varanasi",
        "state": "Uttar Pradesh",
        "country": "India",
        "latitude": 25.3176,
        "longitude": 82.9739,
        "hero_image_url": "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Spirituality, Ganga ghats, temples",
        "description": "One of the world's oldest living cities, spiritual heart of India renowned for sacred Ganga Aarti, mystical sunrise boat rides, and ancient shrines.",
        "rating": 4.8,
        "best_time_to_visit": "October–March",
        "ideal_stay": "2–3 days",
        "budget_per_day": "₹1,000–₹4,000/day",
        "estimated_budget_tier": "₹1,000–₹4,000/day",
        "weather_temperature": "22°C",
        "weather_condition": "Mild & Pleasant",
        "safety_score": 89,
        "tags": ["Spiritual", "Heritage", "Culture", "Food", "Popular", "Trending"],
        "top_attractions": ["Kashi Vishwanath Temple", "Dashashwamedh Ghat", "Assi Ghat", "Manikarnika Ghat", "Sarnath"],
        "activities": ["Ganga Aarti", "Boat ride", "Temple visits", "Heritage walks"],
        "famous_food": ["Kachori sabzi", "Lassi", "Chaat", "Banarasi paan"],
        "local_transport": ["Auto", "E-rickshaw", "Boat", "Taxi"],
        "nearby_places": ["Sarnath", "Prayagraj", "Ayodhya"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "udaipur",
        "name": "Udaipur",
        "state": "Rajasthan",
        "country": "India",
        "latitude": 24.5854,
        "longitude": 73.7125,
        "hero_image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Lakes, palaces, romantic tourism",
        "description": "The romantic City of Lakes crowned with white marble palaces, shimmering Pichola waters, royal courtyards, and scenic mountain backdrops.",
        "rating": 4.9,
        "best_time_to_visit": "October–March",
        "ideal_stay": "2–3 days",
        "budget_per_day": "₹1,500–₹5,000/day",
        "estimated_budget_tier": "₹1,500–₹5,000/day",
        "weather_temperature": "24°C",
        "weather_condition": "Serene & Clear",
        "safety_score": 95,
        "tags": ["Heritage", "Culture", "Romantic", "Food", "Popular", "Trending"],
        "top_attractions": ["City Palace", "Lake Pichola", "Jag Mandir", "Sajjangarh Palace", "Fateh Sagar Lake"],
        "activities": ["Boat rides", "Palace tours", "Photography", "Cultural shows"],
        "famous_food": ["Dal baati churma", "Gatte ki sabzi", "Kachori"],
        "local_transport": ["Auto", "Taxi", "Cabs"],
        "nearby_places": ["Mount Abu", "Jodhpur", "Jaipur"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "manali",
        "name": "Manali",
        "state": "Himachal Pradesh",
        "country": "India",
        "latitude": 32.2432,
        "longitude": 77.1892,
        "hero_image_url": "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Mountains, snow, adventure",
        "description": "Himalayan adventure haven nestled in the Beas River valley, renowned for snow sports, pine forests, Rohtang Pass, and scenic treks.",
        "rating": 4.8,
        "best_time_to_visit": "March–June (pleasant), December–February (snow)",
        "ideal_stay": "3–5 days",
        "budget_per_day": "₹1,500–₹5,000/day",
        "estimated_budget_tier": "₹1,500–₹5,000/day",
        "weather_temperature": "12°C",
        "weather_condition": "Cool & Mountain Air",
        "safety_score": 94,
        "tags": ["Mountains", "Adventure", "Nature", "Popular", "Trending"],
        "top_attractions": ["Solang Valley", "Rohtang region", "Hidimba Temple", "Old Manali", "Mall Road"],
        "activities": ["Trekking", "Skiing", "Paragliding", "Rafting", "Snow activities"],
        "famous_food": ["Siddu", "Thukpa", "Momos"],
        "local_transport": ["Bus", "Taxi", "Local cabs"],
        "nearby_places": ["Kasol", "Kullu", "Manikaran"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "rishikesh",
        "name": "Rishikesh",
        "state": "Uttarakhand",
        "country": "India",
        "latitude": 30.0869,
        "longitude": 78.2676,
        "hero_image_url": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Yoga, spirituality and adventure",
        "description": "World Capital of Yoga on the emerald Ganges foothills, famous for white-water rafting, tranquil ashrams, cliff jumping, and spiritual aartis.",
        "rating": 4.8,
        "best_time_to_visit": "September–June",
        "ideal_stay": "2–3 days",
        "budget_per_day": "₹1,000–₹4,000/day",
        "estimated_budget_tier": "₹1,000–₹4,000/day",
        "weather_temperature": "21°C",
        "weather_condition": "Fresh Mountain Breeze",
        "safety_score": 96,
        "tags": ["Spiritual", "Adventure", "Mountains", "Food", "Popular", "Trending"],
        "top_attractions": ["Laxman Jhula area", "Ram Jhula", "Triveni Ghat", "Beatles Ashram", "Neer Garh Waterfall"],
        "activities": ["River rafting", "Bungee jumping", "Yoga", "Camping"],
        "famous_food": ["North Indian food", "Cafés", "Vegetarian dishes"],
        "local_transport": ["Auto", "Vikram", "Taxis"],
        "nearby_places": ["Haridwar", "Mussoorie", "Dehradun"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "shimla",
        "name": "Shimla",
        "state": "Himachal Pradesh",
        "country": "India",
        "latitude": 31.1048,
        "longitude": 77.1734,
        "hero_image_url": "https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Hill station, snow, colonial architecture",
        "description": "Former British summer capital perched amidst cedar ridges, featuring the heritage Ridge, Mall Road, colonial churches, and scenic toy trains.",
        "rating": 4.7,
        "best_time_to_visit": "March–June (pleasant), December–February (snow)",
        "ideal_stay": "2–3 days",
        "budget_per_day": "₹1,500–₹5,000/day",
        "estimated_budget_tier": "₹1,500–₹5,000/day",
        "weather_temperature": "14°C",
        "weather_condition": "Crisp Mountain Chill",
        "safety_score": 95,
        "tags": ["Mountains", "Heritage", "Adventure", "Shopping", "Popular"],
        "top_attractions": ["Mall Road", "Ridge", "Christ Church", "Jakhoo Temple", "Kufri"],
        "activities": ["Snow activities", "Hiking", "Sightseeing", "Shopping"],
        "famous_food": ["Chana Madra", "Dhaam", "Sidu", "Momos"],
        "local_transport": ["Toy Train", "Buses", "Taxis"],
        "nearby_places": ["Kufri", "Chail", "Manali"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "kochi",
        "name": "Kochi",
        "state": "Kerala",
        "country": "India",
        "latitude": 9.9312,
        "longitude": 76.2673,
        "hero_image_url": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Backwaters, heritage, Kerala culture",
        "description": "The Queen of the Arabian Sea featuring cantilevered Chinese fishing nets, Portuguese spice warehouses, Dutch palaces, and serene backwaters.",
        "rating": 4.8,
        "best_time_to_visit": "October–March",
        "ideal_stay": "2–3 days",
        "budget_per_day": "₹1,500–₹5,000/day",
        "estimated_budget_tier": "₹1,500–₹5,000/day",
        "weather_temperature": "27°C",
        "weather_condition": "Tropical Sea Breeze",
        "safety_score": 96,
        "tags": ["Heritage", "Culture", "Beaches", "Food", "Popular"],
        "top_attractions": ["Fort Kochi", "Chinese fishing nets", "Mattancherry Palace", "Jew Town", "Marine Drive"],
        "activities": ["Backwater cruises", "Heritage walks", "Food tours"],
        "famous_food": ["Appam", "Kerala fish curry", "Puttu", "Seafood"],
        "local_transport": ["Metro", "Ferries", "Auto", "Taxis"],
        "nearby_places": ["Alleppey", "Munnar", "Kumarakom"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "bangalore",
        "name": "Bangalore",
        "state": "Karnataka",
        "country": "India",
        "latitude": 12.9716,
        "longitude": 77.5946,
        "hero_image_url": "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Technology, gardens, cafés and nightlife",
        "description": "The Garden City & Silicon Valley of India, famed for year-round pleasant weather, expansive botanical parks, craft breweries, and thriving café culture.",
        "rating": 4.7,
        "best_time_to_visit": "October–February",
        "ideal_stay": "2–3 days",
        "budget_per_day": "₹1,500–₹5,000/day",
        "estimated_budget_tier": "₹1,500–₹5,000/day",
        "weather_temperature": "23°C",
        "weather_condition": "Pleasant & Breezy",
        "safety_score": 93,
        "tags": ["Food", "Culture", "Nightlife", "Shopping", "Popular"],
        "top_attractions": ["Bangalore Palace", "Lalbagh", "Cubbon Park", "Vidhana Soudha", "ISKCON Temple"],
        "activities": ["Café hopping", "Nightlife", "Shopping", "City tours"],
        "famous_food": ["Dosa", "Idli", "Filter coffee", "Biryani"],
        "local_transport": ["Namma Metro", "Buses", "Auto", "Cabs"],
        "nearby_places": ["Mysuru", "Coorg", "Nandi Hills"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "hyderabad",
        "name": "Hyderabad",
        "state": "Telangana",
        "country": "India",
        "latitude": 17.3850,
        "longitude": 78.4867,
        "hero_image_url": "https://images.unsplash.com/photo-1605379399642-870262d3d051?auto=format&fit=crop&w=1200&q=80",
        "known_for": "History, architecture and food",
        "description": "City of Pearls balancing 400-year-old Qutb Shahi heritage, Charminar, Golconda acoustic fortress, modern tech hubs, and world-famous Biryani.",
        "rating": 4.8,
        "best_time_to_visit": "October–February",
        "ideal_stay": "2–3 days",
        "budget_per_day": "₹1,200–₹4,000/day",
        "estimated_budget_tier": "₹1,200–₹4,000/day",
        "weather_temperature": "26°C",
        "weather_condition": "Sunny",
        "safety_score": 92,
        "tags": ["Heritage", "Food", "Culture", "Shopping", "Popular"],
        "top_attractions": ["Charminar", "Golconda Fort", "Hussain Sagar", "Chowmahalla Palace", "Salar Jung Museum"],
        "activities": ["Heritage tours", "Food tours", "Shopping"],
        "famous_food": ["Hyderabadi biryani", "Haleem", "Kebabs", "Double ka meetha"],
        "local_transport": ["Metro", "Auto", "Buses", "Cabs"],
        "nearby_places": ["Warangal"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "kolkata",
        "name": "Kolkata",
        "state": "West Bengal",
        "country": "India",
        "latitude": 22.5726,
        "longitude": 88.3639,
        "hero_image_url": "https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Culture, literature, colonial heritage and food",
        "description": "The City of Joy and cultural soul of India, known for colonial marble monuments, literary salons, vintage trams, grand bridges, and unmatched sweets.",
        "rating": 4.7,
        "best_time_to_visit": "October–March",
        "ideal_stay": "2–3 days",
        "budget_per_day": "₹1,200–₹4,000/day",
        "estimated_budget_tier": "₹1,200–₹4,000/day",
        "weather_temperature": "24°C",
        "weather_condition": "Comfortable & Mild",
        "safety_score": 93,
        "tags": ["Culture", "Heritage", "Food", "Shopping", "Popular"],
        "top_attractions": ["Victoria Memorial", "Howrah Bridge", "Indian Museum", "St. Paul's Cathedral", "Park Street"],
        "activities": ["Heritage walks", "Food tours", "Cultural experiences"],
        "famous_food": ["Kathi rolls", "Mishti doi", "Rasgulla", "Fish curry"],
        "local_transport": ["Metro", "Yellow Taxis", "Trams", "Ferries"],
        "nearby_places": ["Darjeeling", "Sundarbans"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "chennai",
        "name": "Chennai",
        "state": "Tamil Nadu",
        "country": "India",
        "latitude": 13.0827,
        "longitude": 80.2707,
        "hero_image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Beaches, temples and South Indian culture",
        "description": "Gateway to South India featuring the world's second-longest urban beach, towering Dravidian temple gopurams, Carnatic music, and filter coffee.",
        "rating": 4.7,
        "best_time_to_visit": "November–February",
        "ideal_stay": "2–3 days",
        "budget_per_day": "₹1,200–₹4,000/day",
        "estimated_budget_tier": "₹1,200–₹4,000/day",
        "weather_temperature": "28°C",
        "weather_condition": "Warm & Coastal",
        "safety_score": 94,
        "tags": ["Beaches", "Spiritual", "Heritage", "Culture", "Food", "Popular"],
        "top_attractions": ["Marina Beach", "Kapaleeshwarar Temple", "Fort St. George", "San Thome Basilica"],
        "activities": ["Beach visits", "Temple tours", "Cultural experiences", "Shopping"],
        "famous_food": ["Dosa", "Idli", "Sambar", "Filter coffee"],
        "local_transport": ["Metro", "Suburban trains", "Auto", "Cabs"],
        "nearby_places": ["Mahabalipuram", "Pondicherry"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "amritsar",
        "name": "Amritsar",
        "state": "Punjab",
        "country": "India",
        "latitude": 31.6340,
        "longitude": 74.8723,
        "hero_image_url": "https://images.unsplash.com/photo-1588096344356-9a22d86f99cb?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Golden Temple, history and Punjabi culture",
        "description": "Sacred Sikh spiritual center, home to the breathtaking Harmandir Sahib (Golden Temple), poignant Jallianwala Bagh, and electric Wagah Border ceremony.",
        "rating": 4.9,
        "best_time_to_visit": "October–March",
        "ideal_stay": "2 days",
        "budget_per_day": "₹1,000–₹4,000/day",
        "estimated_budget_tier": "₹1,000–₹4,000/day",
        "weather_temperature": "20°C",
        "weather_condition": "Sunny & Crisp",
        "safety_score": 96,
        "tags": ["Spiritual", "Heritage", "Culture", "Food", "Popular", "Trending"],
        "top_attractions": ["Golden Temple", "Jallianwala Bagh", "Wagah Border", "Partition Museum"],
        "activities": ["Temple visit", "Food tours", "Heritage tours"],
        "famous_food": ["Amritsari kulcha", "Chole", "Lassi", "Tandoori food"],
        "local_transport": ["Auto", "E-rickshaws", "Cabs"],
        "nearby_places": ["Wagah", "Chandigarh"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "jodhpur",
        "name": "Jodhpur",
        "state": "Rajasthan",
        "country": "India",
        "latitude": 26.2389,
        "longitude": 73.0243,
        "hero_image_url": "https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Blue City, forts and royal heritage",
        "description": "Rajasthan's iconic Sun City with indigo-washed old quarters, the colossal cliff-top Mehrangarh Fort, marble cenotaphs, and Thar Desert adventures.",
        "rating": 4.8,
        "best_time_to_visit": "October–March",
        "ideal_stay": "2–3 days",
        "budget_per_day": "₹1,500–₹4,500/day",
        "estimated_budget_tier": "₹1,500–₹4,500/day",
        "weather_temperature": "25°C",
        "weather_condition": "Clear Sky",
        "safety_score": 94,
        "tags": ["Heritage", "Culture", "Shopping", "Food", "Adventure", "Popular"],
        "top_attractions": ["Mehrangarh Fort", "Jaswant Thada", "Umaid Bhawan Palace", "Clock Tower Market"],
        "activities": ["Fort tours", "Photography", "Shopping", "Desert experiences"],
        "famous_food": ["Makhaniya lassi", "Mirchi bada", "Dal baati"],
        "local_transport": ["Auto", "Taxis", "Walking"],
        "nearby_places": ["Jaisalmer", "Udaipur", "Jaipur"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "mysuru",
        "name": "Mysuru",
        "state": "Karnataka",
        "country": "India",
        "latitude": 12.2958,
        "longitude": 76.6394,
        "hero_image_url": "https://images.unsplash.com/photo-1600100397608-f010f444f2b9?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Palaces, culture and Dasara",
        "description": "Heritage royal capital of the Wodeyars, famed for the grand illuminated Mysore Palace, aromatic sandalwood, silk sarees, and vibrant Dasara festivities.",
        "rating": 4.8,
        "best_time_to_visit": "October–February",
        "ideal_stay": "2 days",
        "budget_per_day": "₹1,200–₹4,000/day",
        "estimated_budget_tier": "₹1,200–₹4,000/day",
        "weather_temperature": "24°C",
        "weather_condition": "Pleasant",
        "safety_score": 95,
        "tags": ["Heritage", "Culture", "Shopping", "Food", "Popular"],
        "top_attractions": ["Mysore Palace", "Chamundi Hills", "Brindavan Gardens", "St. Philomena's Church"],
        "activities": ["Palace tours", "Cultural sightseeing", "Shopping"],
        "famous_food": ["Mysore pak", "Dosa", "South Indian meals"],
        "local_transport": ["Auto", "KSRTC Buses", "Cabs"],
        "nearby_places": ["Coorg", "Bengaluru", "Ooty"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "darjeeling",
        "name": "Darjeeling",
        "state": "West Bengal",
        "country": "India",
        "latitude": 27.0410,
        "longitude": 88.2663,
        "hero_image_url": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
        "known_for": "Tea gardens, mountains and Toy Train",
        "description": "The Queen of the Hills overlooking Mount Kanchenjunga, world-famous emerald tea estates, UNESCO heritage steam toy trains, and Tibetan culture.",
        "rating": 4.8,
        "best_time_to_visit": "March–May, October–December",
        "ideal_stay": "2–4 days",
        "budget_per_day": "₹1,500–₹5,000/day",
        "estimated_budget_tier": "₹1,500–₹5,000/day",
        "weather_temperature": "13°C",
        "weather_condition": "Crisp Mountain Mist",
        "safety_score": 95,
        "tags": ["Mountains", "Nature", "Heritage", "Food", "Adventure", "Popular"],
        "top_attractions": ["Tiger Hill", "Darjeeling Himalayan Railway", "Batasia Loop", "Himalayan Mountaineering Institute", "Tea gardens"],
        "activities": ["Trekking", "Tea tours", "Toy Train ride", "Mountain sightseeing"],
        "famous_food": ["Momos", "Thukpa", "Tibetan cuisine"],
        "local_transport": ["Shared jeeps", "Taxis"],
        "nearby_places": ["Kalimpong", "Gangtok"],
        "is_popular": True,
        "is_featured": True
    },
    {
        "id": "puducherry",
        "name": "Puducherry",
        "state": "Puducherry",
        "country": "India",
        "latitude": 11.9416,
        "longitude": 79.8083,
        "hero_image_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
        "known_for": "French architecture, beaches, cafés and relaxed tourism",
        "description": "Charming French colonial coastal haven with pastel villas, cobblestone boulevards, peaceful seaside promenade, Auroville township, and serene beaches.",
        "rating": 4.8,
        "best_time_to_visit": "October–March",
        "ideal_stay": "2–3 days",
        "budget_per_day": "₹1,500–₹5,000/day",
        "estimated_budget_tier": "₹1,500–₹5,000/day",
        "weather_temperature": "27°C",
        "weather_condition": "Balmy Sea Breeze",
        "safety_score": 94,
        "tags": ["Beaches", "Culture", "Heritage", "Food", "Spiritual", "Popular"],
        "top_attractions": ["White Town", "Promenade Beach", "Auroville", "Sri Aurobindo Ashram", "Paradise Beach"],
        "activities": ["Café hopping", "Cycling", "Beach visits", "Photography"],
        "famous_food": ["French cuisine", "South Indian food", "Seafood"],
        "local_transport": ["Bicycles", "Rented scooters", "Auto"],
        "nearby_places": ["Mahabalipuram", "Chennai"],
        "is_popular": True,
        "is_featured": True
    }
]

DESTINATIONS_JSON = json.dumps(DESTINATIONS_DATA, indent=2)
