# Enterprise Firestore Models - Re-exported for Seamless API Compatibility
from app.models.firestore_models import (
    FirestoreEntity,
    User,
    UserProfile,
    TravelPreferences,
    EmergencyContact,
    Destination,
    PlaceAttraction,
    DayPassBundle,
    Review,
    Trip,
    TripDay,
    TripActivity,
    DisruptionLog,
    PackingItem,
    Booking,
    PaymentTransaction,
    Refund,
    SOSAlert,
    LostPhoneSession,
    SeparatedGroup,
    GroupMember,
    CommunityForum,
    CommunityPost,
    CommunityComment,
    CreatorItinerary,
    SupportTicket,
    TicketMessage,
    Notification,
    AuditLog,
    IdempotencyRecord,
    AIGenerationLog,
    AIFeedback,
)

# Compatibility aliases
TimeStampedBase = FirestoreEntity
SavedCollection = FirestoreEntity
SavedItem = FirestoreEntity
UserSession = FirestoreEntity

__all__ = [
    "FirestoreEntity",
    "TimeStampedBase",
    "User",
    "UserProfile",
    "TravelPreferences",
    "EmergencyContact",
    "Destination",
    "PlaceAttraction",
    "DayPassBundle",
    "Review",
    "Trip",
    "TripDay",
    "TripActivity",
    "DisruptionLog",
    "PackingItem",
    "Booking",
    "PaymentTransaction",
    "Refund",
    "SOSAlert",
    "LostPhoneSession",
    "SeparatedGroup",
    "GroupMember",
    "CommunityForum",
    "CommunityPost",
    "CommunityComment",
    "CreatorItinerary",
    "SupportTicket",
    "TicketMessage",
    "Notification",
    "AuditLog",
    "IdempotencyRecord",
    "AIGenerationLog",
    "AIFeedback",
    "SavedCollection",
    "SavedItem",
    "UserSession",
]
